name: 'Get and Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
inputs: 
  caching:
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Use the cache data'
    value: echo ${{steps.out-cache.outputs.outputCache}}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
    - name: Output Cache data
      id: out-cache
      run: echo "outputCache=${{inputs.caching}}" >> $GITHUB_OUTPUT
      shell: bash